// import Head from 'next/head'
// import styles from '../styles/Home.module.css'
// import Link from 'next/link'
import Main from './../components/main/main'

const Home = () => {
  return <Main />
  
}

// const Home = ({ posts }) => {

//   posts = posts ? posts : [];

//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <h1 className={styles.title}>
//         Welcome to <a href="https://nextjs.org">Next.js!</a>
//       </h1>
//       <div>This is home page</div>
//       <Link href='/about'><button><a>about page</a></button></Link>

//       <div className={{ maxHeight: "300px", overflow: "auto" }}>
//         {
//           posts.map((item, index) => (
//             <div key={index}>
//               <div>{item.title}</div>
//               <div>{item.body}</div>
//               <Link href='/article/[title]/[pid]' as={`/article/${item.title}/${item.id}`}>
//                 <button className='px-3 mx-2 rounded text-white text-center bg-gray-500 font-bold drop-shadow hover:bg-gray-600 active:bg-gray-700 focus:ring focus:ring-gray-300'>
//                   <a>page article with this data</a>
//                 </button>
//               </Link>
//             </div>
//           ))
//         }
//       </div>
//     </div>
//   )

// }

// export async function getServerSideProps() {
//   // Fetch data from external API
//   const res = await fetch(`https://jsonplaceholder.typicode.com/posts`)
//   const posts = await res.json()

//   // Pass data to the page via props
//   return { props: { posts } }
// }

export default Home;
